spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.31.11:3306/yjc-test?allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&characterSetResults=UTF-8&maxReconnects=10&useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      minIdle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
  freemarker:
      request-context-attribute: request
      settings:
        date_format: yyyy-MM-dd
        datetime_format: yyyy-MM-dd HH:mm:ss
        time_format: HH:mm:ss
        number_format: 0
  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

#文件基础路径
web:
  upload-path: src\\main\\webapp\\article
#web:
#  upload-path: /mnt/smcy/article

server:
#8100-8200
  port: 80
#  port: ${random.int[10011,10020]}

shiro:
  loginUrl: /login
  successUrl: /admin/reportinfo/list
  unauthorizedUrl: /403

wechat:
  mp:
    host: http://hywy.ngrok.sourcespro.cn
    appId: wx478166d8b34fa488
    secret: 3dd89a8d26859198940cf2c84801a6ab
    token: yijiance
    aesKey: t6OzKty8FZGnwe6eYqyZm3M4ECHIEW3FXcwiaAtWKMi
  pay:
    appId: wx478166d8b34fa488
    mchId: 1490013342
    mchKey: fdwiraranrn434KHFHIDNV3jdkabvcby
    keyPath:

logging:
  level:
    org.springframework: info

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dk.crm.entity
  # typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
      table-prefix: t_
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
