spring:
  datasource:
    druid:
      url:  jdbc:mysql://47.104.148.228:3306/test_dev?allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8&characterSetResults=UTF-8&maxReconnects=10&useSSL=false&serverTimezone=UTC
      username: admin
      password: 1qaz@wsx3EDC
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      minIdle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
  freemarker:
      request-context-attribute: request
      settings:
        date_format: yyyy-MM-dd
        datetime_format: yyyy-MM-dd HH:mm:ss
        time_format: HH:mm:ss
        number_format: 0
  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

server:
#8100-8200
  port: 8102
#  port: ${random.int[10011,10020]}

shiro:
  loginUrl: /login
  successUrl: /admin/reportinfo/list
  unauthorizedUrl: /403

wechat:
#  host: http://trip.sourcespro.cn
  mp:
#    host: http://k6hb28.natappfree.cc
    appid: wx172b0f6c2085127d
    secret: 77e9a79bde004a424d2f1025484e0918
    token: a36cd8d390d504623b97d3f70f3cc479

logging:
  level:
    org.springframework: info



#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.crm.entity
  # typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
      table-prefix: t_
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
